### ISSUE TITLE
Propose a patch to your bash version of run-parts

### ISSUE THREAD

**Issue by bakerjalexander** [ikysil/run-parts#1]
Thanks for your work. I used this to run a bash version of a kernel hook script and it worked great, but unfortunately it barfed on using the init script for apparmor because the init script called the --lsbsysinit argument to run-parts - which your version didn't have.

So I wrote a patch to add --lsbsysinit and --regex support. Try it out see if it works for you.

Thanks again
[run-parts-lsbsysinit.patch.txt](https://github.com/ikysil/run-parts/files/4775965/run-parts-lsbsysinit.patch.txt)

**Comment by ikysil** [comment]
Applied with small corrections - only the basename of the script is verified with `--lsbsysinit` and `--regex` options.
